# Generated by Django 4.0.4 on 2023-11-25 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('amount_of_users', models.IntegerField()),
                ('song', models.CharField(max_length=255)),
                ('timer', models.IntegerField()),
            ],
        ),
    ]
