# Generated by Django 4.0.2 on 2023-09-27 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Homework_result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dz', models.IntegerField(default=0)),
                ('number', models.IntegerField(default=0)),
                ('code', models.TextField()),
                ('is_approved', models.BooleanField(default=False)),
            ],
        ),
    ]
