# Generated by Django 4.0.4 on 2023-11-25 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_songn'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Songn',
            new_name='Song',
        ),
    ]
